<?php
return [
    'id' => 1,
    'name' => 'SUN HOTEL',
    'address' => 'Đền lừ, Hoàng Mai',
    'email' => 'sun@hotel.com',
    'phone' => '0956658565',
    'description_vi' => 'Đẳng cấp chất lượng Phục vụ tận tình tận tâm là phương châm của khách sạn đẳng cấp',
    'description_en' => "We'll bring the best things for you!",
    'social' => [
        'twitter' => '#',
        'facebook' => '#',
        'rss' => '#',
        'google-plus' => '#',
        'linkedIn' => '#',
    ],
    'gallery' => [
        'small-img',
        'small-img-2',
        'small-img-4',
        'small-img-5',
        'small-img-3',
        'small-img-6',
    ],
    'prefix_booking_code' => 'MS2020',
    'currency' => 'đ',
    'url_avatar_default' => 'img/avatar/',
    'url_room_default' => 'img/room/',
    'avatar_user_default' => 'default.png',
    'image_room_default' => 'default.png',
    'star_num' => 5,
];
